package br.com.dataupa.gui;

import br.com.dataupa.bns.Paciente;
import br.com.dataupa.utl.DbMock;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
//import sun.swing.table.DefaultTableCellHeaderRenderer;

public class PacienteListar extends javax.swing.JInternalFrame {

    /**
     * Creates new form PacienteConsultar
     */
    public PacienteListar() {
        initComponents();
        carregaTabelaPacientes();
    }

    public static void atualizaListaPacientes(Paciente paciente) {
        pacientes.add(paciente);
    }

    static List<Paciente> pacientes = DbMock.pacientes;

    public void carregaTabelaPacientes() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NOME");
        modelo.addColumn("SEXO");
        modelo.addColumn("DATA NASC.");
        modelo.addColumn("RG");
        modelo.addColumn("CPF");
        modelo.addColumn("CIDADE");

        /*
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellHeaderRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTablePacientes.setDefaultRenderer(Object.class, centerRenderer);
         */
        if (pacientes != null) {
            for (Paciente paciente : pacientes) {
                modelo.addRow(new String[]{
                    paciente.getNome(), paciente.getSexo(), paciente.getDataNasc(),
                    paciente.getRg(), paciente.getCpf(),
                    paciente.getEndereco().getCidade()
                });
            }
        }

        jTablePacientes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePacientes = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();

        setTitle("DATAUPA 1.0 - Lista de Pacientes");

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePacientes.setViewportView(jTablePacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanePacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPanePacientes;
    private javax.swing.JTable jTablePacientes;
    // End of variables declaration//GEN-END:variables
}
