package br.com.dataupa.gui;

import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBarSistema = new javax.swing.JMenuBar();
        jMenuAcesso = new javax.swing.JMenu();
        jMenuItemAceAlterarSenha = new javax.swing.JMenuItem();
        jMenuItemAceDesconectar = new javax.swing.JMenuItem();
        jMenuAtendimento = new javax.swing.JMenu();
        jMenuItemPacCadastrarPaciente = new javax.swing.JMenuItem();
        jMenuItemPacListarPacientes = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DATAUPA 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        jMenuAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/control_panel_access.png"))); // NOI18N
        jMenuAcesso.setText("Acesso");

        jMenuItemAceAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/change_password.png"))); // NOI18N
        jMenuItemAceAlterarSenha.setText("Alterar Senha");
        jMenuItemAceAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAceAlterarSenhaActionPerformed(evt);
            }
        });
        jMenuAcesso.add(jMenuItemAceAlterarSenha);

        jMenuItemAceDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/exit.png"))); // NOI18N
        jMenuItemAceDesconectar.setText("Desconectar");
        jMenuItemAceDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAceDesconectarActionPerformed(evt);
            }
        });
        jMenuAcesso.add(jMenuItemAceDesconectar);

        jMenuBarSistema.add(jMenuAcesso);

        jMenuAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/acess.png"))); // NOI18N
        jMenuAtendimento.setText("Atendimento");

        jMenuItemPacCadastrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/script_add.png"))); // NOI18N
        jMenuItemPacCadastrarPaciente.setText("Cadastrar Paciente");
        jMenuItemPacCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacCadastrarPacienteActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemPacCadastrarPaciente);

        jMenuItemPacListarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/script.png"))); // NOI18N
        jMenuItemPacListarPacientes.setText("Listar Pacientes");
        jMenuItemPacListarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacListarPacientesActionPerformed(evt);
            }
        });
        jMenuAtendimento.add(jMenuItemPacListarPacientes);

        jMenuBarSistema.add(jMenuAtendimento);

        jMenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/cgr.png"))); // NOI18N
        jMenuRelatorio.setText("Relatório");
        jMenuBarSistema.add(jMenuRelatorio);

        jMenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/help.png"))); // NOI18N
        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/dataupa/res/ico/information.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBarSistema.add(jMenuAjuda);

        setJMenuBar(jMenuBarSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Deseja finalizar o sistema?", "Finalizar - DATAUPA", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            setDefaultCloseOperation(Sistema.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(Sistema.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemAceAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAceAlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAceAlterarSenhaActionPerformed

    private void jMenuItemAceDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAceDesconectarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Deseja sair?", "Logoff - DATAUPA", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jMenuItemAceDesconectarActionPerformed

    private void jMenuItemPacCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacCadastrarPacienteActionPerformed
        // TODO add your handling code here:
        try {
            // Remover todos os JInternalFrame do JDesktopPane
            jDesktop.removeAll();

            // Instanciando o frame interno
            PacienteCadastrar pacienteCadastrar = new PacienteCadastrar();

            // Formatação para remover o top left drop down (arrow)
            BasicInternalFrameUI ui = (BasicInternalFrameUI) pacienteCadastrar.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();

            // Adiciona o JInternalFrame ao JDesktopPane
            jDesktop.add(pacienteCadastrar);

            // Inicia o JInternalFrame Maximizado
            pacienteCadastrar.setMaximum(true);
            //frame.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());

            // Carrega o JInternalFrame
            pacienteCadastrar.show();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemPacCadastrarPacienteActionPerformed

    private void jMenuItemPacListarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacListarPacientesActionPerformed
        // TODO add your handling code here:
        try {
            // Remover todos os JInternalFrame do JDesktopPane
            jDesktop.removeAll();

            // Instanciando o frame interno
            PacienteListar pacienteConsultar = new PacienteListar();

            // Formatação para remover o top left drop down (arrow)
            BasicInternalFrameUI ui = (BasicInternalFrameUI) pacienteConsultar.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();

            // Adiciona o JInternalFrame ao JDesktopPane
            jDesktop.add(pacienteConsultar);

            // Inicia o JInternalFrame Maximizado
            pacienteConsultar.setMaximum(true);
            //frame.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());

            // Carrega o JInternalFrame
            pacienteConsultar.show();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemPacListarPacientesActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
        new Sobre().setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenuAcesso;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBarSistema;
    private javax.swing.JMenuItem jMenuItemAceAlterarSenha;
    private javax.swing.JMenuItem jMenuItemAceDesconectar;
    private javax.swing.JMenuItem jMenuItemPacCadastrarPaciente;
    private javax.swing.JMenuItem jMenuItemPacListarPacientes;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuRelatorio;
    // End of variables declaration//GEN-END:variables
}
